namespace Markwardt.AssetPipeline.Client.ViewModels;

/// <summary>
/// An <see cref="AssetVariantViewModel"/> generated by an <see cref="ImageNodeViewModel"/>.
/// </summary>
internal sealed partial class ImageVariantViewModel : AssetVariantViewModel
{
    /// <summary>
    /// Initializes a new instance of the <see cref="ImageVariantViewModel"/> class.
    /// </summary>
    public ImageVariantViewModel(string id, string name, VariantStatus status, DateTimeOffset createdAt, string? errorMessage = null)
        : base(id, name, status, createdAt, errorMessage)
    {
    }

    [ObservableProperty]
    private string? outputFilePath;

    /// <inheritdoc />
    public override AssetVariant ToModel() => new ImageVariant
    {
        Id = Id,
        Name = Name,
        Status = Status,
        CreatedAt = CreatedAt,
        ErrorMessage = ErrorMessage,
        OutputFilePath = OutputFilePath,
    };

    partial void OnOutputFilePathChanged(string? value) => RaiseChanged();
}
