namespace Markwardt.AssetPipeline.Client.ViewModels;

/// <summary>
/// An <see cref="AssetVariantViewModel"/> generated by a <see cref="MeshNodeViewModel"/>. Each variant
/// first gets its own concept image and then, once approved (if the owning node requires it), its own 3D
/// mesh generated from that concept image.
/// </summary>
internal sealed partial class MeshVariantViewModel : AssetVariantViewModel
{
    /// <summary>
    /// Initializes a new instance of the <see cref="MeshVariantViewModel"/> class.
    /// </summary>
    public MeshVariantViewModel(string id, string name, VariantStatus status, DateTimeOffset createdAt, string? errorMessage = null)
        : base(id, name, status, createdAt, errorMessage)
    {
    }

    [ObservableProperty]
    private string? conceptImagePath;

    [ObservableProperty]
    private string? outputFilePath;

    /// <summary>
    /// Gets or sets this variant's concept image's full, resolved path on disk (not persisted - re-derived
    /// from <see cref="ConceptImagePath"/> and the owning node's output folder whenever it changes), used to
    /// preview the concept image for approval.
    /// </summary>
    public string? AbsoluteConceptImagePath { get; set; }

    /// <inheritdoc />
    public override AssetVariant ToModel() => new MeshVariant
    {
        Id = Id,
        Name = Name,
        Status = Status,
        CreatedAt = CreatedAt,
        ErrorMessage = ErrorMessage,
        ConceptImagePath = ConceptImagePath,
        OutputFilePath = OutputFilePath,
    };

    partial void OnConceptImagePathChanged(string? value) => RaiseChanged();

    partial void OnOutputFilePathChanged(string? value) => RaiseChanged();
}
