namespace Markwardt.AssetPipeline.Client.Core.Models;

/// <summary>
/// An <see cref="AssetVariant"/> generated by an <see cref="ImageNode"/>.
/// </summary>
internal sealed record ImageVariant : AssetVariant
{
    /// <summary>
    /// Gets the generated image's file path, relative to the owning <see cref="ImageNode.OutputPath"/>, or
    /// <see langword="null"/> if generation has not completed.
    /// </summary>
    public string? OutputFilePath { get; init; }
}
