namespace Markwardt.AssetPipeline.Client.Core.Models;

/// <summary>
/// An <see cref="AssetVariant"/> generated by a <see cref="MeshNode"/>. Each variant first gets its own
/// concept image (from scenario.com) and then, once approved (if the owning node requires it), its own 3D
/// mesh generated from that concept image (from meshy.ai).
/// </summary>
internal sealed record MeshVariant : AssetVariant
{
    /// <summary>
    /// Gets this variant's concept image file path, relative to the owning <see cref="MeshNode.OutputPath"/>,
    /// or <see langword="null"/> if the concept image has not been generated yet.
    /// </summary>
    public string? ConceptImagePath { get; init; }

    /// <summary>
    /// Gets the generated mesh's file path, relative to the owning <see cref="MeshNode.OutputPath"/>, or
    /// <see langword="null"/> if mesh generation has not completed.
    /// </summary>
    public string? OutputFilePath { get; init; }
}
