namespace Markwardt.AssetPipeline.Client.Core.Models;

/// <summary>
/// An <see cref="AssetVariant"/> generated by a <see cref="TextNode"/>.
/// </summary>
internal sealed record TextVariant : AssetVariant
{
    /// <summary>
    /// Gets the generated text's file path, relative to the owning <see cref="TextNode.OutputPath"/>, or
    /// <see langword="null"/> if generation has not completed.
    /// </summary>
    public string? OutputFilePath { get; init; }
}
